# Generated by Django 4.0.6 on 2022-07-30 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia_integrantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='parentesco',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
