# Generated by Django 4.0.6 on 2022-07-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familia_integrantes', '0002_familia_parentesco'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
